modLoader="javafml"
loaderVersion="[36,)"
license="LGPL-2.1-only"

[[mods]]
modId="skysgrassslabsintegrationtest"
version="1"
displayName="Sky's Grass Slabs Integration Test"
description='''Build-only gameplay, world generation and upgrade fixture.'''

[[dependencies.skysgrassslabsintegrationtest]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="SERVER"

[[dependencies.skysgrassslabsintegrationtest]]
modId="skysgrassslabs"
mandatory=true
versionRange="[1.0.1.116051]"
ordering="AFTER"
side="SERVER"

[[dependencies.skysgrassslabsintegrationtest]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5]"
ordering="NONE"
side="SERVER"
