org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.configuration-cache=false
org.gradle.caching=true
org.gradle.parallel=false
net.minecraftforge.gradle.merge-source-sets=false

minecraft_version=1.16.5
minecraft_version_range=[1.16.5,1.17)
forge_version=36.2.34
forge_version_range=[36,)
loader_version_range=[36,)
mapping_channel=official
mapping_version=1.16.5
mcp_version=20210115.111550

loader_name=forge
loader_code=1
java_version=8
java_toolchain_version=8.0.502+7
gradle_java_version=17
curseforge_project_id=1677588

mod_id=skysgrassslabs
mod_name=Sky's Grass Slabs
mod_license=LGPL-2.1-only
mod_version=1.0.1.116051
mod_group=zone.moddev.mc.skysgrassslabs
mod_authors=SkyBlade1978
mod_description=Adds dirt, grass and path slabs, turf, natural grass spreading and smoother Overworld terrain.
