modLoader="javafml"
loaderVersion="[36,)"
license="LGPL-2.1-only"

[[mods]]
modId="skysgrassslabsclienttest"
version="1"
displayName="Sky's Grass Slabs Client Probe"
description='''Build-only rendered client and world reload fixture.'''

[[dependencies.skysgrassslabsclienttest]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="CLIENT"

[[dependencies.skysgrassslabsclienttest]]
modId="skysgrassslabs"
mandatory=true
versionRange="[1.0.1.116051]"
ordering="AFTER"
side="CLIENT"

[[dependencies.skysgrassslabsclienttest]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5]"
ordering="NONE"
side="CLIENT"
